module Orghunter
  class Geolocation
    attr_reader :ein, :name, :inCareOfName, :street, :city, :state, :zipCode, :country, :groupExemption, :subsection, :classification, :affiliation, :rullingDate, :deductibility, :deductibilityStatus, :foundation, :activity1, :activity2, :activity3, :organization, :exemptStatus, :taxPeriod, :assetCodeDesc, :incomeCodeDesc, :filingRequirementCodeDesc, :pfFilingRequirementCodeDesc, :accountingPeriod, :assetAmount, :incomeAmount, :form990, :nteeCd, :nteeClass, :nteeType, :sortName, :revocationDt, :revPostingDt, :irsRevocationStatus, :acceptingDonations, :latitude, :longitude

    def initialize(args)
      @ein = args["ein"]
      @name = args["name"]
      @category = args["category"]
      @in_care_of = args["inCareOfName"]
      @street = args['street']
      @city = args["city"]
      @state = args["state"]
      @zip_code = args["zipCode"]
      @country = args['country']
      @groupExemption = args['groupExemption']
      @subsection = args['subsection']
      @classification = args['classification']
      @affiliation = args['affiliation']
      @ruling_date = args['rullingDate']
      @deductibility = args['deductibility']
      @deductibility_status = args['deductibilityStatus']
      @foundation = args['foundation']
      @activity1 = args['activity1']
      @activity2 = args['activity2']
      @activity3 = args['activity3']
      @organization = args['organization']
      @exempt_status = args['exemptStatus']
      @tax_period = args['taxPeriod']
      @asset_code_desc = args['assetCodeDesc']
      @income_code_desc = args['incomeCodeDesc']
      @filing_requirement_code_desc = args['filingRequirementCodeDesc ']
      @pf_filing_requirement_code_desc = args["pfFilingRequirementCodeDesc"]
      @accounting_period = args["accountingPeriod"]
      @asset_amount = args["assetAmount"]
      @income_amount = args["incomeAmount"]
      @form990 = args["form990"]
      @ntee_cd = args['nteeCd']
      @ntee_class = args["nteeClass"]
      @ntee_type = args["nteeType"]
      @sortName = args["sortName"]
      @revocationDt = args["revocationDt"]
      @revPostingDt = args["revPostingDt"]
      @irsRevocationStatus = args["irsRevocationStatus"]
      @accepting_donations = args["acceptingDonations"]
      @latitude = args["latitude"]
      @longitude = args["longitude"]
    end
  end
end
