module Orghunter
  class Geolocation
    attr_reader :ein, :name, :in_care_of, :street, :city, :state, :zip_code, :country, :group_exemption, :subsection, :classification, :affiliation, :ruling_date, :deductibility, :deductibility_status, :foundation, :activity1, :activity2, :activity3, :organization, :exempt_status, :tax_period, :asset_code_desc, :income_code_desc, :filing_requirement_code_desc, :pf_filing_requirement_code_desc, :accounting_period, :asset_amount, :income_amount, :form990, :ntee_cd, :ntee_class, :ntee_type, :sort_name, :revocation_dt, :rev_posting_dt, :irs_revocation_status, :accepting_donations, :latitude, :longitude

    def initialize(args)
      @ein = args["ein"]
      @name = args["name"]
      @in_care_of = args["inCareOfName"]
      @street = args['street']
      @city = args["city"]
      @state = args["state"]
      @zip_code = args["zipCode"]
      @country = args['country']
      @group_exemption = args['groupExemption']
      @subsection = args['subsection']
      @classification = args['classification']
      @affiliation = args['affiliation']
      @ruling_date = args['rullingDate']
      @deductibility = args['deductibility']
      @deductibility_status = args['deductibilityStatus']
      @foundation = args['foundation']
      @activity1 = args['activity1']
      @activity2 = args['activity2']
      @activity3 = args['activity3']
      @organization = args['organization']
      @exempt_status = args['exemptStatus']
      @tax_period = args['taxPeriod']
      @asset_code_desc = args['assetCodeDesc']
      @income_code_desc = args['incomeCodeDesc']
      @filing_requirement_code_desc = args['filingRequirementCodeDesc ']
      @pf_filing_requirement_code_desc = args["pfFilingRequirementCodeDesc"]
      @accounting_period = args["accountingPeriod"]
      @asset_amount = args["assetAmount"]
      @income_amount = args["incomeAmount"]
      @form990 = args["form990"]
      @ntee_cd = args['nteeCd']
      @ntee_class = args["nteeClass"]
      @ntee_type = args["nteeType"]
      @sort_name = args["sortName"]
      @revocation_dt = args["revocationDt"]
      @rev_posting_dt = args["revPostingDt"]
      @irs_revocation_status = args["irsRevocationStatus"]
      @accepting_donations = args["acceptingDonations"]
      @latitude = args["latitude"]
      @longitude = args["longitude"]
    end
  end
end
